apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'user@example.com'
      smtp_auth_password: 'password'
    
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'team-email'
      routes:
      - match:
          severity: 'critical'
        receiver: 'team-pager'
    
    receivers:
    - name: 'team-email'
      email_configs:
      - to: 'team@example.com'
    
    - name: 'team-pager'
      pagerduty_configs:
      - service_key: 'your-pagerduty-key'
    
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster']