apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app: monitoring-stack
resources:
  - namespace.yaml
  - prometheus/
  - alertmanager/
  - grafana/
  - kube-state-metrics/
  - node-exporter/